---
resources:
- name: github
  type: git
  source:
    uri: https://github.com/jschirrmacher/Rocket.Chat.git
    branch: develop

jobs:
- name: build
  public: true
  plan:

  - get: github
    trigger: true

  - task: install
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node/carbon}
      inputs:
        - name: github
      outputs:
        - name: installed
      run:
        path: github/.concourse/install.sh

- name: test
  public: true
  plan:
  
  - task: lint
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
        - name: installed
      run:
        path: meteor npm run lint

  - task: stylelint
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
        - name: installed
      run:
        path: meteor npm run stylelint

  - task: unittests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
        - name: installed
      run:
        path: meteor npm run testunit
