---
resources:
- name: github
  type: git
  source:
    uri: https://github.com/jschirrmacher/Rocket.Chat.git
    branch: develop

jobs:
- name: rocketchat
  public: true
  plan:

  - get: github
    trigger: true

  - task: install-meteor
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
        - name: github
      run:
        path: github/.concourse/install-meteor.sh
